#!/bin/bash

ARGS=$(getopt -o i:o:m:n: --long input:,output:,rows:,cols: -n 'gridpdf' -- "$@")
if [ $? -ne 0 ]; then
  echo "error"
  exit 1
fi

eval set -- "$ARGS"

input=""
output="output.pdf"
rows=2
cols=2

while true; do
  case "$1" in
    -i|--input)
      input="$2"
      shift 2
      ;;
    -o|--output)
      output="$2"
      shift 2
      ;;
    -m|--rows)
      rows="$2"
      shift 2
      ;;
    -n|--cols)
      cols="$2"
      shift 2
      ;;
    --)
      shift
      break
      ;;
    *)
      echo "unknown: $1"
      exit 1
      ;;
  esac
done

if [ -z "$input" ]; then
  echo "how-to:"
  echo "  $0 -i input.pdf -o output.pdf -m 2 -n 2"
  exit 1
fi

pdfjam --nup "$cols"x"$rows" --paper a4paper --landscape "$input" --outfile "$output"

if [ $? -eq 0 ]; then
  echo "succ: $output"
else
  echo "failed"
fi
